spring:
  profiles:
    active: dev

faster:
  secret:
    enabled: true
    decryptionKeyFilePath: E:\IdeaProjects\demo\mastercard\src\test\resources\crypto\myPrivateKey.key
    aaa-bbb-ccc: abb

master:
  api:
    env: mtf
    majorVer: 1
    minorVer: 0