server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.mvc.mapper

# log
logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace
    com:
      example:
        mvc :
          mapper : debug
