# Tomcat配置
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8082
  connection-timeout: 5000ms
  servlet:
    context-path: /
spring:
  application:
    name: mybatis-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/portal?useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 123456
    hikari:
      pool-name: DatebookHikariCP
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lzp.demo.entity
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl